default: &default
  home_url: <%= ENV["HOME_URL"] %>
  participacio_url:
    ca: <%= ENV["PARTICIPACIO_URL_CA"] %>
    es: <%= ENV["PARTICIPACIO_URL_ES"] %>
  registration_url:
    ca: <%= ENV["USER_REGISTRATION_URL_CA"] %>
    es: <%= ENV["USER_REGISTRATION_URL_ES"] %>
  managers:
    contact_data: <%= ENV["CATCOMU_CONTACTS"] %>
  civicrm:
    auto_sync_groups: [12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 40, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]
    private_processes:
      - slug: inscrites-alt-pirineu
        group_name: Alt Pirineu i Aran
        group_type: inscrites
        group_id: 12
        ref: AT-I-APA
      - slug: inscrites-baix-llobregat
        group_name: Baix Llobregat
        group_type: inscrites
        group_id: 14
        ref: AT-I-BL
      - slug: inscrites-barcelones
        group_name: Barcelones
        group_type: inscrites
        group_id: 15
        ref: AT-I-B
      - slug: inscrites-camp-de-tarragona
        group_name: Camp De Tarragona
        group_type: inscrites
        group_id: 16
        ref: AT-I-CT
      - slug: inscrites-catalunya-central
        group_name: Catalunya Central
        group_type: inscrites
        group_id: 17
        ref: AT-I-CC
      - slug: inscrites-comarques-gironines
        group_name: Comarques Gironines
        group_type: inscrites
        group_id: 18
        ref: AT-I-CG
      - slug: inscrites-maresme
        group_name: Maresme
        group_type: inscrites
        group_id: 19
        ref: AT-I-M
      - slug: inscrites-penedes
        group_name: Penedes
        group_type: inscrites
        group_id: 20
        ref: AT-I-P
      - slug: inscrites-ponent
        group_name: Ponent
        group_type: inscrites
        group_id: 21
        ref: AT-I-L
      - slug: inscrites-terres-de-lebre
        group_name: Terres De L'ebre
        group_type: inscrites
        group_id: 22
        ref: AT-I-E
      - slug: inscrites-valles-occidental
        group_name: Valles Occidental
        group_type: inscrites
        group_id: 23
        ref: AT-I-VOC
      - slug: inscrites-valles-oriental
        group_name: Valles Oriental
        group_type: inscrites
        group_id: 24
        ref: AT-I-VOR
      - slug: executiva-alt-pirineu
        group_name: Alt Pirineu
        group_id: 142
        group_type: executiva
        ref: AT-E-APA
      - slug: executiva-baix-llobregat
        group_name: Baix Llobregat
        group_id: 138
        group_type: executiva
        ref: AT-E-BL
      - slug: executiva-barcelones
        group_name: Barcelones
        group_id: 146
        group_type: executiva
        ref: AT-E-B
      - slug: executiva-camp-de-tarragona
        group_name: Camp De Tarragona
        group_id: 147
        group_type: executiva
        ref: AT-E-CT
      - slug: executiva-catalunya-central
        group_name: Catalunya Central
        group_id: 139
        group_type: executiva
        ref: AT-E-CC
      - slug: executiva-comarques-gironines
        group_name: Comarques Gironines
        group_id: 145
        group_type: executiva
        ref: AT-E-CG
      - slug: executiva-maresme
        group_name: Maresme
        group_id: 149
        group_type: executiva
        ref: AT-E-M
      - slug: executiva-penedes
        group_name: Penedes
        group_id: 144
        group_type: executiva
        ref: AT-E-P
      - slug: executiva-ponent
        group_name: Ponent
        group_id: 143
        group_type: executiva
        ref: AT-E-L
      - slug: executiva-terres-de-lebre
        group_name: Terres De L'ebre
        group_id: 148
        group_type: executiva
        ref: AT-E-E
      - slug: executiva-valles-occidental
        group_name: Valles Occidental
        group_id: 140
        group_type: executiva
        ref: AT-E-VOC
      - slug: executiva-valles-oriental
        group_name: Valles Oriental
        group_id: 141
        group_type: executiva
        ref: AT-E-VOR

development:
  <<: *default
  civicrm:
    auto_sync_groups: [40]
    private_processes:
      - slug: inscrites-alt-pirineu
        group_name: Alt Pirineu i Aran
        group_type: inscrites
        group_id: 12
        ref: AT-I-APA

test:
  <<: *default
  home_url: http://home.url
  participacio_url:
    en: http://home.url
  registration_url:
    en: http://registration.url

production:
  <<: *default
