# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: ca

## All available locales are inferred from the data by default. Alternatively, specify them explicitly:
locales: [ca, es]

## Reporting locale, default: en. Available: en, ru.
# internal_locale: en

data:
  read:
    - config/locales/%{locale}.yml
    - catcomu-managers/config/locales/%{locale}.yml
    - decidim-civicrm/config/locales/%{locale}.yml
  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1
  external:
    - "<%= %x[bundle info decidim-core --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-participatory_processes --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-assemblies --path].chomp %>/config/locales/%{locale}.yml"



# Find translate calls
search:
  ## If `strict` is `false`, guess usages such as t("categories.#{category}.title"). The default is `true`.
  strict: false

# Consider these keys used (modifications of the original translation from core
# or keys automatically generated by code)
ignore_unused:
  - decidim.account.show.email_readonly_explanation
  - decidim.authorization_handlers.civicrm.explanation
  - decidim.authorization_handlers.civicrm.fields.regional_scope
  - decidim.authorization_handlers.civicrm.fields.regional_scope_choices.*
  - decidim.authorization_handlers.civicrm.fields.role
  - decidim.authorization_handlers.civicrm.fields.role_choices.*
  - decidim.authorization_handlers.civicrm.name
  - decidim.authorization_handlers.direct_verifications.explanation
  - decidim.authorization_handlers.direct_verifications.name
  - decidim.authorization_handlers.groups.explanation
  - decidim.authorization_handlers.groups.name
  - decidim.components.proposals.actions.comment
  - decidim.events.civicrm_verification.errors.invalid_method
  - decidim.events.civicrm_verification.errors.invalid_status
  - decidim.events.civicrm_verification.invalid.email_intro
  - decidim.events.civicrm_verification.invalid.email_outro
  - decidim.events.civicrm_verification.invalid.email_subject
  - decidim.events.civicrm_verification.invalid.notification_title
  - decidim.events.civicrm_verification.ok.email_intro
  - decidim.events.civicrm_verification.ok.email_outro
  - decidim.events.civicrm_verification.ok.email_subject
  - decidim.events.civicrm_verification.ok.notification_title
  - decidim.navigation_maps.content_blocks.name
  - decidim.scope_ungrouped_processes.menu
  - decidim.system.organizations.omniauth_settings.civicrm.client_id
  - decidim.system.organizations.omniauth_settings.civicrm.client_secret
  - decidim.system.organizations.omniauth_settings.civicrm.site
  - decidim.system.organizations.omniauth_settings.enabled_by_default
  - decidim.verifications.authorizations.first_login.actions.civicrm
  - devise.shared.links.sign_in_with_provider
  - layouts.decidim.user_profile.my_data
