# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  home_url: <%= ENV["HOME_URL"] %>
  participacio_url:
    ca: <%= ENV["PARTICIPACIO_URL_CA"] %>
    es: <%= ENV["PARTICIPACIO_URL_ES"] %>
  registration_url:
    ca: <%= ENV["USER_REGISTRATION_URL_CA"] %>
    es: <%= ENV["USER_REGISTRATION_URL_ES"] %>
  # duplicate processes landing and show all processes belonging to any group there
  scope_ungrouped_processes: 
    key: menu # used to search a I18n key and a route path
    position_in_menu: 2.1
    enabled: true # set to false to deactivate
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      icon_path: decidim/brands/google.svg
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>      
    civicrm:
      enabled: <%= ENV["CIVICRM_CLIENT_ID"] ? "true" : "false" %>
      client_id: <%= ENV["CIVICRM_CLIENT_ID"] %>
      client_secret: <%= ENV["CIVICRM_CLIENT_SECRET"] %>
      site: <%= ENV["CIVICRM_SITE"] %>
      icon_path: catencomu/Isotip.jpg
  geocoder:
    here_api_key: <%= ENV["GEOCODER_API_KEY"] %>
  managers:
    contact_data: <%= ENV["CATCOMU_CONTACTS"] %>
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>
    api_version: "1.2.1"
  civicrm:
    api:
      url: <%= ENV["CIVICRM_VERIFICATION_URL"] %>
      key: <%= ENV["CIVICRM_VERIFICATION_API_KEY"] %>
      secret: <%= ENV["CIVICRM_VERIFICATION_SECRET"] %>
    auto_sync_groups: [12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 40, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]
    private_processes:
      - slug: inscrites-alt-pirineu
        group_name: Alt Pirineu i Aran
        group_type: inscrites
        group_id: 12
        ref: AT-I-APA
      - slug: inscrites-baix-llobregat
        group_name: Baix Llobregat
        group_type: inscrites
        group_id: 14
        ref: AT-I-BL
      - slug: inscrites-barcelones
        group_name: Barcelones
        group_type: inscrites
        group_id: 15
        ref: AT-I-B
      - slug: inscrites-camp-de-tarragona
        group_name: Camp De Tarragona
        group_type: inscrites
        group_id: 16
        ref: AT-I-CT
      - slug: inscrites-catalunya-central
        group_name: Catalunya Central
        group_type: inscrites
        group_id: 17
        ref: AT-I-CC
      - slug: inscrites-comarques-gironines
        group_name: Comarques Gironines
        group_type: inscrites
        group_id: 18
        ref: AT-I-CG
      - slug: inscrites-maresme
        group_name: Maresme
        group_type: inscrites
        group_id: 19
        ref: AT-I-M
      - slug: inscrites-penedes
        group_name: Penedes
        group_type: inscrites
        group_id: 20
        ref: AT-I-P
      - slug: inscrites-ponent
        group_name: Ponent
        group_type: inscrites
        group_id: 21
        ref: AT-I-L
      - slug: inscrites-terres-de-lebre
        group_name: Terres De L'ebre
        group_type: inscrites
        group_id: 22
        ref: AT-I-E
      - slug: inscrites-valles-occidental
        group_name: Valles Occidental
        group_type: inscrites
        group_id: 23
        ref: AT-I-VOC
      - slug: inscrites-valles-oriental
        group_name: Valles Oriental
        group_type: inscrites
        group_id: 24
        ref: AT-I-VOR
      - slug: executiva-alt-pirineu
        group_name: Alt Pirineu
        group_id: 142
        group_type: executiva
        ref: AT-E-APA
      - slug: executiva-baix-llobregat
        group_name: Baix Llobregat
        group_id: 138
        group_type: executiva
        ref: AT-E-BL
      - slug: executiva-barcelones
        group_name: Barcelones
        group_id: 146
        group_type: executiva
        ref: AT-E-B
      - slug: executiva-camp-de-tarragona
        group_name: Camp De Tarragona
        group_id: 147
        group_type: executiva
        ref: AT-E-CT
      - slug: executiva-catalunya-central
        group_name: Catalunya Central
        group_id: 139
        group_type: executiva
        ref: AT-E-CC
      - slug: executiva-comarques-gironines
        group_name: Comarques Gironines
        group_id: 145
        group_type: executiva
        ref: AT-E-CG
      - slug: executiva-maresme
        group_name: Maresme
        group_id: 149
        group_type: executiva
        ref: AT-E-M
      - slug: executiva-penedes
        group_name: Penedes
        group_id: 144
        group_type: executiva
        ref: AT-E-P
      - slug: executiva-ponent
        group_name: Ponent
        group_id: 143
        group_type: executiva
        ref: AT-E-L
      - slug: executiva-terres-de-lebre
        group_name: Terres De L'ebre
        group_id: 148
        group_type: executiva
        ref: AT-E-E
      - slug: executiva-valles-occidental
        group_name: Valles Occidental
        group_id: 140
        group_type: executiva
        ref: AT-E-VOC
      - slug: executiva-valles-oriental
        group_name: Valles Oriental
        group_id: 141
        group_type: executiva
        ref: AT-E-VOR
development:
  <<: *default
  secret_key_base: b5f1327eed88f30f5739073f7ae63167a83e90875506afe784f4dcede64c537182079d40c0ee4cb4ffefc283bd2721e748336571e272e573f656340e958aed2f
  omniauth:
    developer:
      enabled: true
      icon: phone
    civicrm:
      enabled: <%= ENV["CIVICRM_CLIENT_ID"] ? "true" : "false" %>
      client_id: <%= ENV["CIVICRM_CLIENT_ID"] %>
      client_secret: <%= ENV["CIVICRM_CLIENT_SECRET"] %>
      site: <%= ENV["CIVICRM_SITE"] %>
      icon_path: catencomu/Isotip.jpg
  civicrm:
    api:
      url: <%= ENV["CIVICRM_VERIFICATION_URL"] %>
      key: <%= ENV["CIVICRM_VERIFICATION_API_KEY"] %>
      secret: <%= ENV["CIVICRM_VERIFICATION_SECRET"] %>
    auto_sync_groups: [40]
    private_processes:
      - slug: inscrites-alt-pirineu
        group_name: Alt Pirineu i Aran
        group_type: inscrites
        group_id: 12
        ref: AT-I-APA

test:
  <<: *default
  secret_key_base: 031b356d569468dfa4fa20822d2c02f55ad399d87720d42a380f981f3cf671084b2460ddd3194a4cd47f82cd593906025d081686bcab2e60ab31de4a61e5e826
  home_url: http://home.url
  participacio_url: 
    en: http://home.url
  registration_url: 
    en: http://registration.url
  omniauth:
    facebook:
      enabled: true
      app_id: fake-facebook-app-id
      app_secret: fake-facebook-app-secret
    twitter:
      enabled: true
      api_key: fake-twitter-api-key
      api_secret: fake-twitter-api-secret
    google_oauth2:
      enabled: true
      client_id:
      client_secret:
    civicrm:
      enabled: true
      client_id: fake-civicrm-client-id
      client_secret: fake-civicrm-client-secret
      site: fake-civicrm-url.com
  civicrm:
    api:
      url: https://api.base
      key: api-key
      secret: secret

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
