name: Build

on:
  push:
    branches:
      - master
  pull_request:

env:
  RUBY_VERSION: 2.6.6

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Setup & create Database
        run: |
          bundle exec rake decidim:generate_external_test_app
          bundle exec rails db:create db:schema:load

      - name: Precompile assets
        run: bundle exec rake assets:precompile

      # - name: Setup Code Climate test-reporter
      #   run: |
      #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #     chmod +x ./cc-test-reporter
      #     ./cc-test-reporter before-build

      - name: Run RSpec
        run: SIMPLECOV=1 CODECOV=1 bundle exec rake

      # - name: Publish code coverage
      #   run: |
      #     export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
      #     ./cc-test-reporter after-build -r "$CC_TEST_REPORTER_ID"
      #   env:
      #     CC_TEST_REPORTER_ID: dc93f2c0d045a6fd7b2d2a9b03dfaf2c3b298c520605744bc0283a7535d5dc92