name: Lint

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 3.0.6
  NODE_VERSION: 16.20.2

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci
        name: Install JS deps

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      - run: bundle exec mdl *.md
        name: Lint Markdown files

      - run: bundle exec erblint {decidim-module-catcomu_managers/,}app/{cells,views}/**/*.erb
        name: Lint ERB files

      - run: npm run stylelint
        name: Lint SCSS files

      - run: npm run lint
        name: Lint JS files
